# Generated by Django 4.1.7 on 2023-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_myuser_libid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='libid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
