# Generated by Django 4.1.7 on 2023-03-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='sid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
