# Generated by Django 4.1.7 on 2023-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_rent_bid_alter_rent_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
