# Generated by Django 4.1.7 on 2023-06-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_book_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.RemoveField(
            model_name='book',
            name='libid',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='libid',
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
