# Generated by Django 4.1.7 on 2023-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_delete_library_remove_book_libid_remove_myuser_libid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='dor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
