# Generated by Django 4.1.7 on 2023-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_rent_dor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
